# Generated by Django 5.2.8 on 2025-12-12 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0004_alter_game_options_alter_gamecomment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('pc', 'PC'), ('ps', 'PlayStation'), ('xbox', 'Xbox'), ('switch', 'Nintendo Switch'), ('other', 'Другое')], default='pc', max_length=20, verbose_name='Платформа')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('code', models.TextField(verbose_name='Код / последовательность действий')),
                ('description', models.TextField(blank=True, verbose_name='Описание / комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheats', to='games.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'чит',
                'verbose_name_plural': 'читы',
                'ordering': ['game', 'platform', 'title'],
            },
        ),
    ]
