# Generated by Django 5.2.8 on 2026-01-30 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cheat',
            options={'ordering': ['-updated_at'], 'verbose_name': 'чит', 'verbose_name_plural': 'читы'},
        ),
        migrations.RemoveField(
            model_name='cheat',
            name='code',
        ),
        migrations.RemoveField(
            model_name='cheat',
            name='description',
        ),
        migrations.AddField(
            model_name='cheat',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cheats', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cheat',
            name='cheat_file',
            field=models.FileField(blank=True, null=True, upload_to='cheat_files/', verbose_name='Файл чита/тренера'),
        ),
        migrations.AddField(
            model_name='cheat',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cheat_covers/', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='cheat',
            name='downloads_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Скачивания'),
        ),
        migrations.AddField(
            model_name='cheat',
            name='functionality',
            field=models.TextField(blank=True, verbose_name='Функционал'),
        ),
        migrations.AddField(
            model_name='cheat',
            name='instruction',
            field=models.TextField(blank=True, verbose_name='Инструкция'),
        ),
        migrations.AddField(
            model_name='cheat',
            name='liked_percent',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Понравилось'),
        ),
        migrations.AddField(
            model_name='cheat',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='cheat',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='cheat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AddField(
            model_name='cheat',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='cheat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='cheat',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='cheat',
            name='platform',
            field=models.CharField(choices=[('pc', 'PC'), ('ps', 'PlayStation'), ('xbox', 'Xbox'), ('switch', 'Switch'), ('mobile', 'Mobile'), ('other', 'Другое')], default='pc', max_length=20, verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='cheat',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='CheatComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалён')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Отредактирован')),
                ('cheat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cheats.cheat', verbose_name='Чит')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheat_comments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'комментарий к читу',
                'verbose_name_plural': 'комментарии к читам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheatVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'Лайк'), (-1, 'Дизлайк')], verbose_name='Оценка')),
                ('cheat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='cheats.cheat', verbose_name='Чит')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheat_votes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'оценка чита',
                'verbose_name_plural': 'оценки читов',
                'unique_together': {('user', 'cheat')},
            },
        ),
    ]
