# Generated by Django 5.2.8 on 2025-12-14 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='conclusion',
            field=models.TextField(blank=True, verbose_name='Итог'),
        ),
        migrations.AddField(
            model_name='review',
            name='cons',
            field=models.TextField(blank=True, verbose_name='Минусы'),
        ),
        migrations.AddField(
            model_name='review',
            name='pros',
            field=models.TextField(blank=True, verbose_name='Плюсы'),
        ),
        migrations.AddField(
            model_name='review',
            name='summary',
            field=models.TextField(blank=True, help_text='1–3 предложения: кому зайдёт, кому нет', verbose_name='Коротко (TL;DR)'),
        ),
        migrations.AddField(
            model_name='review',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на видео (YouTube / VK / Rutube)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Основной текст обзора'),
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='review_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.review')),
            ],
            options={
                'verbose_name': 'изображение обзора',
                'verbose_name_plural': 'изображения обзора',
                'ordering': ['order', 'id'],
            },
        ),
    ]
