# Generated by Django 5.2.8 on 2025-12-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_conclusion_review_cons_review_pros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
