# Generated by Django 5.2.8 on 2026-01-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_liked_percent_alter_review_conclusion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='review_covers/', verbose_name='Обложка обзора'),
        ),
    ]
