# Generated by Django 5.2.8 on 2026-01-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcomment',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
