# Generated by Django 5.2.8 on 2026-01-21 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_reviewcomment_is_edited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'комментарий к игре', 'verbose_name_plural': 'комментарии к обзорам'},
        ),
        migrations.AlterModelOptions(
            name='reviewimage',
            options={'ordering': ['order'], 'verbose_name': 'картинка для обзора', 'verbose_name_plural': 'картинка для обзоров'},
        ),
        migrations.AlterField(
            model_name='reviewcomment',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.review', verbose_name='Обзор'),
        ),
        migrations.AlterField(
            model_name='reviewcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(upload_to='review_images/', verbose_name='Добавить изображение'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Номер картинки'),
        ),
        migrations.AlterField(
            model_name='reviewvote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='reviewvote',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reviews.review', verbose_name='Обзор'),
        ),
        migrations.AlterField(
            model_name='reviewvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
