# Generated by Django 5.2.8 on 2026-01-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_reviewcomment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcomment',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Изменен'),
        ),
        migrations.AlterField(
            model_name='reviewvote',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'Лайк'), (-1, 'Дизлайк')], verbose_name='Оценка'),
        ),
    ]
