# Generated by Django 5.2.8 on 2025-11-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(blank=True, default='default_game_cover.jpg', null=True, upload_to='game_covers/', verbose_name='Обложка'),
        ),
    ]
