# Generated by Django 5.2.8 on 2025-12-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-created_at'], 'verbose_name': 'игра', 'verbose_name_plural': 'игры'},
        ),
        migrations.AlterModelOptions(
            name='gamecomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'комментарий к игре', 'verbose_name_plural': 'комментарии к играм'},
        ),
        migrations.AlterModelOptions(
            name='gamevote',
            options={'verbose_name': 'оценка игры', 'verbose_name_plural': 'оценки игр'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'жанр', 'verbose_name_plural': 'жанры'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['name'], 'verbose_name': 'платформа', 'verbose_name_plural': 'платформы'},
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=220, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='URL'),
        ),
    ]
