# Generated by Django 5.2.8 on 2025-12-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_developer_publisher_game_developer_game_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='is_adult_only',
            field=models.BooleanField(default=False, verbose_name='Контент 16+'),
        ),
    ]
