# Generated by Django 5.2.8 on 2025-12-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_is_adult_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='game',
            name='vote_ratio',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
