# Generated by Django 5.2.8 on 2025-12-14 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_game_avg_rating_game_vote_ratio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='vote_ratio',
            new_name='liked_percent',
        ),
    ]
