# Generated by Django 5.2.8 on 2025-12-20 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_rename_vote_ratio_game_liked_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, verbose_name='Средний рейтинг'),
        ),
        migrations.AlterField(
            model_name='game',
            name='liked_percent',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Понравилось'),
        ),
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='game_gallery/', verbose_name='Картинка')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='games.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'картинка игры',
                'verbose_name_plural': 'картинки игры',
                'ordering': ['position', 'id'],
            },
        ),
    ]
