# Generated by Django 5.2.8 on 2025-12-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_game_avg_rating_alter_game_liked_percent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameimage',
            options={'ordering': ['position', 'id'], 'verbose_name': 'картинку игры', 'verbose_name_plural': 'картинки игры'},
        ),
        migrations.AddField(
            model_name='game',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на трейлер (YouTube/Vimeo)'),
        ),
    ]
