# Generated by Django 5.2.8 on 2026-01-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_gameimage_options_game_trailer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='image',
            field=models.ImageField(upload_to='game_gallery/', verbose_name='Добавить картинку'),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='№ картинки'),
        ),
    ]
