# Generated by Django 5.2.8 on 2026-01-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_gameimage_caption_alter_gameimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecomment',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
