# Generated by Django 5.2.8 on 2026-01-21 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_gamecomment_is_edited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameimage',
            options={'ordering': ['position'], 'verbose_name': 'картинка для', 'verbose_name_plural': 'картинки игры'},
        ),
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Опубликована на сайте'),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=220, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название игры'),
        ),
        migrations.AlterField(
            model_name='gamecomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлен'),
        ),
        migrations.AlterField(
            model_name='gamecomment',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='games.game', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='gamecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_comments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='image',
            field=models.ImageField(upload_to='game_gallery/', verbose_name='Добавить изображение'),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер картинки'),
        ),
        migrations.AlterField(
            model_name='gamevote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='gamevote',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='games.game', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='gamevote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_votes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='gamevote',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'Лайк'), (-1, 'Дизлайк')], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='Slug'),
        ),
    ]
