# Generated by Django 5.2.8 on 2025-12-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkthrough',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
