# Generated by Django 5.2.8 on 2026-01-25 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughs', '0002_walkthrough_views_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walkthrough',
            name='content',
        ),
        migrations.AddField(
            model_name='walkthrough',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='walkthrough_covers/', verbose_name='Обложка прохождения'),
        ),
        migrations.AddField(
            model_name='walkthrough',
            name='liked_percent',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Понравилось'),
        ),
        migrations.AddField(
            model_name='walkthrough',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='walkthrough',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание прохождения'),
        ),
        migrations.AddField(
            model_name='walkthrough',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='walkthrough',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walkthroughs', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='walkthrough',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='walkthrough',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='walkthrough',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='walkthrough',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='walkthrough',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.CreateModel(
            name='WalkthroughComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалён')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Изменен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walkthrough_comments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('walkthrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='walkthroughs.walkthrough', verbose_name='Прохождение')),
            ],
            options={
                'verbose_name': 'комментарий к прохождению',
                'verbose_name_plural': 'комментарии к прохождениям',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalkthroughImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='walkthrough_images/', verbose_name='Добавить изображение')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Номер картинки')),
                ('walkthrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='walkthroughs.walkthrough', verbose_name='Прохождение')),
            ],
            options={
                'verbose_name': 'картинка для прохождения',
                'verbose_name_plural': 'картинки для прохождений',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WalkthroughVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'Лайк'), (-1, 'Дизлайк')], verbose_name='Оценка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walkthrough_votes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('walkthrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='walkthroughs.walkthrough', verbose_name='Прохождение')),
            ],
            options={
                'verbose_name': 'оценка прохождения',
                'verbose_name_plural': 'оценки прохождений',
                'unique_together': {('user', 'walkthrough')},
            },
        ),
    ]
