# Generated by Django 5.2.8 on 2026-01-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughs', '0003_remove_walkthrough_content_walkthrough_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkthrough',
            name='video_url',
            field=models.URLField(blank=True, max_length=3000, verbose_name='Ссылка на видео'),
        ),
    ]
