# Generated by Django 5.2.8 on 2025-11-20 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='Никнейм')),
                ('profile_image', models.ImageField(default='profile/', null=True, upload_to='profile_images/', verbose_name='Картинка профиля')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Телефон')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрирован')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('is_banned', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
