# Generated by Django 5.2.8 on 2025-11-26 20:09

import users.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=users.encryption.EncryptedDateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
