# Generated by Django 5.2.8 on 2025-11-26 20:27

import users.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=users.encryption.EncryptedCharField(blank=True, max_length=250, null=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=users.encryption.EncryptedCharField(blank=True, max_length=150, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=users.encryption.EncryptedCharField(blank=True, max_length=150, null=True, verbose_name='Фамилия'),
        ),
    ]
