# Generated by Django 5.2.8 on 2025-11-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('users', '0003_profile_email_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, related_name='fans', to='games.genre', verbose_name='Любимые жанры'),
        ),
    ]
