# Generated by Django 5.2.8 on 2025-12-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_favorite_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'профиль', 'verbose_name_plural': 'профили'},
        ),
    ]
