# Generated by Django 5.2.8 on 2026-01-21 19:35

import django.db.models.deletion
import users.encryption
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created'], 'verbose_name': 'профиль', 'verbose_name_plural': 'профили'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=users.encryption.EncryptedCharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='AdminMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('guest_name', models.CharField(blank=True, max_length=120)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('topic', models.CharField(max_length=40)),
                ('topic_custom', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_read', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sender', models.CharField(default='Администрация сайта', max_length=120)),
                ('topic', models.CharField(choices=[('warning', 'Предупреждение'), ('moderation_result', 'Результаты модерации'), ('profile_block', 'Блокировка профиля'), ('sanctions', 'Санкции'), ('other', 'Другое')], default='other', max_length=40)),
                ('title', models.CharField(max_length=140)),
                ('text', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_read', '-created_at'],
            },
        ),
    ]
