# Generated by Django 5.2.8 on 2026-01-22 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_options_alter_profile_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminmessages',
            options={'ordering': ['is_read', '-created_at'], 'verbose_name': 'Сообщение для администрации', 'verbose_name_plural': 'Сообщения для администрации'},
        ),
        migrations.AlterModelOptions(
            name='usermessages',
            options={'ordering': ['is_read', '-created_at'], 'verbose_name': 'Уведомление для пользователя', 'verbose_name_plural': 'Уведомления для пользователей'},
        ),
        migrations.AddField(
            model_name='usermessages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_messages/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='adminmessages',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Гость(email)'),
        ),
        migrations.AlterField(
            model_name='adminmessages',
            name='guest_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Гость(имя)'),
        ),
        migrations.AlterField(
            model_name='adminmessages',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='adminmessages',
            name='message',
            field=models.TextField(verbose_name='Текст обращения'),
        ),
        migrations.AlterField(
            model_name='adminmessages',
            name='topic',
            field=models.CharField(max_length=40, verbose_name='Тема обращения'),
        ),
        migrations.AlterField(
            model_name='adminmessages',
            name='topic_custom',
            field=models.CharField(blank=True, max_length=120, verbose_name='Своя тема обращения'),
        ),
        migrations.AlterField(
            model_name='adminmessages',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='text',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='title',
            field=models.CharField(blank=True, max_length=140, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='topic',
            field=models.CharField(choices=[('warning', 'Предупреждение'), ('moderation_result', 'Результаты модерации'), ('profile_block', 'Блокировка профиля'), ('sanctions', 'Санкции'), ('other', 'Другое')], default='other', max_length=40, verbose_name='Тема сообщения'),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
    ]
