# Generated by Django 5.2.8 on 2026-01-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_adminmessages_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_messages/', verbose_name='Изображение'),
        ),
    ]
