# Generated by Django 5.2.8 on 2026-01-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_adminmessages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='title',
            field=models.CharField(blank=True, max_length=140, verbose_name='Своя тема обращения'),
        ),
    ]
