# Generated by Django 5.2.8 on 2026-01-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_nickname_alter_usermessages_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Отправлено'),
        ),
        migrations.AlterField(
            model_name='adminmessages',
            name='topic',
            field=models.CharField(choices=[('complaint', 'Жалоба'), ('site_bug', 'Ошибка на сайте'), ('suggestion', 'Предложение'), ('account_restore', 'Восстановление аккаунта'), ('question', 'Вопрос'), ('content_moderation', 'Модерация контента'), ('other', 'Другое')], default='other', max_length=40, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Отправлено'),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='sender',
            field=models.CharField(default='Администрация сайта', max_length=120, verbose_name='Отправитель'),
        ),
    ]
