# Generated by Django 5.2.8 on 2026-01-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_adminmessages_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessages',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Показывать'),
        ),
        migrations.AddField(
            model_name='adminmessages',
            name='status',
            field=models.CharField(choices=[('created', 'Создано'), ('in_review', 'На рассмотрении'), ('moderation', 'На модерации'), ('processed', 'Обработано')], default='created', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='usermessages',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Показывать'),
        ),
    ]
