"""
Django settings for game_hunt project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

from cryptography.fernet import Fernet

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ke+pe-&y_rw)!a4k_k&ba5v*^a(m!xv%l+y5(rfb6!bpgs-5%t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    # Подключаем allauth
    'allauth',
    'allauth.account',

    # # Пока не пробуем добавить авторизацию через соцсети
    #  'allauth.socialaccount',
    # # именно через github
    #  'allauth.socialaccount.providers.github',
    # Подключаем свои приложения
    'core.apps.CoreConfig',
    'users.apps.UsersConfig',
    'games.apps.GamesConfig',

]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.LastSeenMiddleware',
]

ROOT_URLCONF = 'game_hunt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Добавили все шаблоны в корень проекта
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'game_hunt.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # стандартный
    'allauth.account.auth_backends.AuthenticationBackend',  # allauth
]

ACCOUNT_AUTHENTICATION_METHOD = 'username_email'  # вход по логину или email
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # можно 'mandatory' для строгой верификации

# Редирект по умолчанию после входа
LOGIN_REDIRECT_URL = 'homepage'

# Редирект по умолчанию после выхода
LOGOUT_REDIRECT_URL = 'homepage'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


# Смена языка сайта
LANGUAGE_CODE = 'ru-Ru'

# Смена часового пояса
TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'

# Путь для медиа-файлов
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Настройки email для отправки писем
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'   # для тестирования в консоли
EMAIL_HOST = os.getenv('EMAIL_HOST')  # smtp сервер
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')

SITE_URL = 'http://127.0.0.1:8000'


ACCOUNT_FORMS = {
    # Используем свою форму регистрации пользователя в forms GameHuntSignupForm
    'signup': 'users.forms.GameHuntSignupForm',
    # Используем свою форму авторизации пользователя в forms GameHuntLoginForm
    'login': 'users.forms.GameHuntLoginForm',
}
# По умолчанию делаем долговечную сессию(закрыли браузер, вход сохранен)
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_REMEMBER_ME = True

# При успешном подтверждении email редирект на account_email_confirmed
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = 'account_email_confirmed'
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = 'account_email_confirmed'

# По-хорошему нужно хранить ключ шифрования в переменных окружения а не в коде
# Забираем из .env ключ шифрования
ENCRYPTION_KEY = os.getenv('ENCRYPTION_KEY')
# Если ключ шифрования не прописан в .env выбрасываем ошибку
if not ENCRYPTION_KEY:
    raise ValueError('ENCRYPTION_KEY is not set in .env')
# Симметричный алгоритм шифрования с секретным ключом, который обеспечивает аутентифицированную криптографию
FERNET = Fernet(ENCRYPTION_KEY.encode())
